actor_checkpoint: /home/catkin_ws/src/franka_cal_sim/python/checkpoints/actor_checkpoint
critic_checkpoint: /home/catkin_ws/src/franka_cal_sim/python/checkpoints/critic_checkpoint
test_actor_checkpoint: "/home/catkin_ws/results/camera_cal_result/checkpoints/actor_checkpoint "
test_critic_checkpoint: "/home/catkin_ws/results/camera_cal_result/checkpoints/critic_checkpoint "
result_path: /home/catkin_ws/src/franka_cal_sim/python/result.txt
test_result_path: /home/catkin_ws/src/franka_cal_sim/python/test_result.txt
kalibr_path: /home/catkin_ws/src/franka_cal_sim/python/kalibr/
python_path: /home/catkin_ws/src/franka_cal_sim/python/
cam_ground_truth: [585.7561,585.7561,320.5,240.5]
imu_cam_ground_truth: [0.06,0.0,-0.1,0.0,0.0,1.5708]
cam_imu_ground_truth: [622.2387,622.2387,320.5,240.5,0.06,0.0,-0.1,0.0,-0.1,1.5708]
action_path: /home/catkin_ws/src/franka_cal_sim/python/action.txt
reward_path: /home/catkin_ws/src/franka_cal_sim/python/reward_loss.png
trans_path: /home/catkin_ws/src/franka_cal_sim/python/trans_loss.png
train_fig_path: /home/catkin_ws/src/franka_cal_sim/python/train.png
test_fig_path: /home/catkin_ws/src/franka_cal_sim/python/test.png
sensor_gazebo_path: /home/catkin_ws/src/franka_ros/franka_description/robots/panda.gazebo.xacro
hand_path: /home/catkin_ws/src/franka_ros/franka_description/robots/hand.xacro
if_calibrate_intrinsic: true
if_change_sensors: false
